"""Authenticated encryption for application document uploads at rest.

New uploads are encrypted before the configured media backend sees their bytes.
Files predating this storage remain readable for backwards compatibility until
`python manage.py encrypt_existing_documents` is run.
"""
from __future__ import annotations

import base64
import hashlib
import logging
import secrets

from cryptography.fernet import Fernet, InvalidToken
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured, SuspiciousFileOperation
from django.core.files.base import ContentFile
from django.core.files.storage import Storage, default_storage
from django.utils.deconstruct import deconstructible

logger = logging.getLogger(__name__)


def _fernet() -> Fernet:
    configured_key = getattr(settings, "FILE_ENCRYPTION_KEY", "")
    if configured_key:
        key = configured_key.encode("ascii")
    else:
        # Domain-separated fallback keeps local installs working and ties the
        # key to the SECRET_KEY, which must be kept stable to preserve files.
        digest = hashlib.sha256(
            b"Matoshree-Cyber/document-files/v1:" + str(settings.SECRET_KEY).encode("utf-8")
        ).digest()
        key = base64.urlsafe_b64encode(digest)
    try:
        return Fernet(key)
    except (TypeError, ValueError) as exc:
        raise ImproperlyConfigured("FILE_ENCRYPTION_KEY must be a valid Fernet key generated by Fernet.generate_key().") from exc


@deconstructible
class EncryptedDocumentStorage(Storage):
    """Encrypt document bytes while delegating storage to Django's configured backend."""

    def _encrypted_backend(self):
        # Encrypted binary documents must use Cloudinary's RAW resource type;
        # the app's default media backend is configured for images.
        if (
            getattr(settings, "CLOUDINARY_CLOUD_NAME", "")
            and getattr(settings, "CLOUDINARY_API_KEY", "")
            and getattr(settings, "CLOUDINARY_API_SECRET", "")
        ):
            from cloudinary_storage.storage import RawMediaCloudinaryStorage
            return RawMediaCloudinaryStorage()
        return default_storage

    def _open(self, name, mode="rb"):
        if mode not in ("rb", "r"):
            raise ValueError("Encrypted document storage is read-only when opening existing files.")
        is_encrypted = self.is_encrypted_name(name)
        backend = self._encrypted_backend() if is_encrypted else default_storage
        raw = backend.open(name, "rb")
        try:
            stored_bytes = raw.read()
        finally:
            raw.close()
        if not is_encrypted:
            # Compatibility path for records uploaded before encryption was enabled.
            return ContentFile(stored_bytes, name=name)
        try:
            plaintext = _fernet().decrypt(stored_bytes)
        except InvalidToken as exc:
            logger.error("Encrypted document could not be authenticated; refusing to return bytes")
            raise SuspiciousFileOperation("This stored document failed its integrity check.") from exc
        display_name = name[len("encrypted-documents/"):] if name.startswith("encrypted-documents/") else name
        if display_name.endswith(".enc"):
            display_name = display_name[:-4]
        return ContentFile(plaintext, name=display_name)

    @staticmethod
    def is_encrypted_name(name):
        # A path marker survives storage backends that normalize file extensions.
        return str(name).replace("\\", "/").startswith("encrypted-documents/")

    def _save(self, name, content):
        prefix = "encrypted-documents/"
        if hasattr(content, "chunks"):
            plaintext = b"".join(content.chunks())
        else:
            plaintext = content.read()
        encrypted = _fernet().encrypt(plaintext)
        # Keep only a vetted extension so protected downloads retain a useful
        # content type. Never store the submitted filename, customer name or
        # application number in the media path.
        submitted_basename = str(name).replace("\\", "/").rsplit("/", 1)[-1]
        extension = submitted_basename.rsplit(".", 1)[-1].casefold() if "." in submitted_basename else ""
        allowed_extensions = {
            "pdf", "png", "jpg", "jpeg", "webp", "gif", "bmp", "tif", "tiff",
            "doc", "docx", "xls", "xlsx", "odt", "ods", "txt", "csv",
        }
        safe_extension = f".{extension}" if extension in allowed_extensions else ""
        encrypted_name = f"{prefix}{secrets.token_hex(24)}{safe_extension}.enc"
        return self._encrypted_backend().save(encrypted_name, ContentFile(encrypted, name=encrypted_name))

    def delete(self, name):
        backend = self._encrypted_backend() if self.is_encrypted_name(name) else default_storage
        backend.delete(name)

    def exists(self, name):
        if self.is_encrypted_name(name):
            return self._encrypted_backend().exists(name)
        # Legacy plaintext files used the application's original default storage.
        # Newly saved documents always receive unique random names in _save().
        return default_storage.exists(name)

    def size(self, name):
        backend = self._encrypted_backend() if self.is_encrypted_name(name) else default_storage
        return backend.size(name)

    def url(self, name):
        # Never expose the underlying document-storage URL through FileField.url.
        # Download access is handled by the permission-checked Django view.
        return ""

    def get_valid_name(self, name):
        return super().get_valid_name(name)

    def get_available_name(self, name, max_length=None):
        # Django's base implementation calls our exists() method.
        return super().get_available_name(name, max_length=max_length)
