# Generated by Django 6.0.2 on 2026-07-04 10:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('category', models.CharField(choices=[('Government Scheme', 'Government Scheme'), ('Recruitment', 'Recruitment'), ('Scholarship', 'Scholarship'), ('Holiday', 'Holiday'), ('Notice', 'Notice')], max_length=50, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, verbose_name='Business Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo')),
                ('welcome_message', models.TextField(verbose_name='Welcome Message')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-15 digits).', regex='^\\+?1?\\d{10,15}$')], verbose_name='Phone')),
                ('whatsapp', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-15 digits).', regex='^\\+?1?\\d{10,15}$')], verbose_name='WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('google_map', models.TextField(help_text='Paste Google Maps Embed Code', verbose_name='Google Map')),
                ('business_hours', models.TextField(verbose_name='Business Hours')),
            ],
            options={
                'verbose_name': 'Business Information',
                'verbose_name_plural': 'Business Information',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-15 digits).', regex='^\\+?1?\\d{10,15}$')], verbose_name='Phone')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('replied', models.BooleanField(default=False, verbose_name='Replied')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('pdf', models.FileField(upload_to='forms/', verbose_name='PDF')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Download Form',
                'verbose_name_plural': 'Download Forms',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('category', models.CharField(choices=[('Cyber Cafe', 'Cyber Cafe'), ('Customers', 'Customers'), ('Certificates', 'Certificates'), ('Equipment', 'Equipment'), ('Office', 'Office')], max_length=50, verbose_name='Category')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
            },
        ),
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('eligibility', models.TextField(blank=True, verbose_name='Eligibility')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Last Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schemes/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Government Scheme',
                'verbose_name_plural': 'Government Schemes',
            },
        ),
        migrations.CreateModel(
            name='JobNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('organization', models.CharField(max_length=200, verbose_name='Organization')),
                ('last_date', models.DateField(verbose_name='Last Date')),
                ('apply_link', models.URLField(blank=True, verbose_name='Apply Link')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(default='briefcase', help_text="Font Awesome icon (e.g. 'fa-briefcase')", max_length=50, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Job Notification',
                'verbose_name_plural': 'Job Notifications',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('review', models.TextField(verbose_name='Review')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Rating')),
                ('approved', models.BooleanField(default=True, verbose_name='Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('icon', models.CharField(default='cog', help_text="Font Awesome icon class (e.g., 'fa-print')", max_length=50, verbose_name='Icon')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='user', max_length=20, verbose_name='Role')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200, verbose_name='Document Name')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corematoshree.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Required Document',
                'verbose_name_plural': 'Required Documents',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-15 digits).', regex='^\\+?1?\\d{10,15}$')], verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('appointment_date', models.DateField(verbose_name='Appointment Date')),
                ('appointment_time', models.TimeField(verbose_name='Appointment Time')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corematoshree.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Charge')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corematoshree.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Charge',
                'verbose_name_plural': 'Service Charges',
            },
        ),
    ]
