# Generated by Django 6.0.2 on 2026-07-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_color',
            field=models.CharField(default='#00d4ff', help_text='Hex color for the icon circle (e.g., #ff6b35)', max_length=7, verbose_name='Icon Color'),
        ),
    ]
