# Generated by Django 6.0.2 on 2026-07-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0002_alter_businessinfo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentscheme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='schemes/'),
        ),
        migrations.AddField(
            model_name='jobnotification',
            name='icon',
            field=models.CharField(default='briefcase', help_text="Font Awesome icon (e.g. 'fa-briefcase')", max_length=50),
        ),
    ]
