# Generated by Django 6.0.2 on 2026-07-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0002_service_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='Reply'),
        ),
    ]
