# Generated by Django 6.0.2 on 2026-07-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0002_alter_announcement_options_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
