# Generated by Django 6.0.2 on 2026-07-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0004_application_documentupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='certifications',
            field=models.TextField(blank=True, help_text='Enter each certification on a new line.', verbose_name='Certifications / Authorizations'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='registration_number',
            field=models.CharField(blank=True, help_text='e.g. UDYAM-XX-00-0000000', max_length=100, verbose_name='Registration Number'),
        ),
    ]
