# Generated by Django 6.0.2 on 2026-07-19 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('corematoshree', '0006_alter_application_phone_alter_appointment_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('Government Scheme', 'Government Scheme'), ('Recruitment', 'Recruitment'), ('Scholarship', 'Scholarship'), ('Holiday', 'Holiday'), ('Notice', 'Notice')], db_index=True, max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10–15 digits).', regex='^\\+?1?\\d{10,15}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(db_index=True, verbose_name='Appointment Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10–15 digits).', regex='^\\+?1?\\d{10,15}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10–15 digits).', regex='^\\+?1?\\d{10,15}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='replied',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Replied'),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='document_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Document Name'),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='is_mandatory',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Mandatory'),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Uploaded At'),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Verified by Admin'),
        ),
        migrations.AlterField(
            model_name='downloadform',
            name='category',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='downloadform',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='downloadform',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Uploaded At'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('Cyber Cafe', 'Cyber Cafe'), ('Customers', 'Customers'), ('Certificates', 'Certificates'), ('Equipment', 'Equipment'), ('Office', 'Office')], db_index=True, max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='last_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Last Date'),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='jobnotification',
            name='last_date',
            field=models.DateField(db_index=True, verbose_name='Last Date'),
        ),
        migrations.AlterField(
            model_name='jobnotification',
            name='organization',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='jobnotification',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='document_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Document Name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(db_index=True, default=5, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='service',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], db_index=True, default='user', max_length=20, verbose_name='Role'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['category', 'created_at'], name='corematoshr_categor_7567ce_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'status'], name='corematoshr_user_id_e001b7_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['service', 'status'], name='corematoshr_service_95d49d_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'created_at'], name='corematoshr_status_22bd5f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['email'], name='corematoshr_email_1a2781_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['phone'], name='corematoshr_phone_7b1790_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'appointment_date'], name='corematoshr_status_348ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['service', 'appointment_date'], name='corematoshr_service_c64c13_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['created_at'], name='corematoshr_created_d384dd_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['replied', 'created_at'], name='corematoshr_replied_0f5a05_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='corematoshr_email_30fdf8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['application', 'verified'], name='corematoshr_applica_cc872f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['document_name'], name='corematoshr_documen_20eb1e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['is_mandatory'], name='corematoshr_is_mand_7735e0_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadform',
            index=models.Index(fields=['category', 'uploaded_at'], name='corematoshr_categor_93056d_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['question'], name='corematoshr_questio_935a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['category'], name='corematoshr_categor_a06f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='governmentscheme',
            index=models.Index(fields=['last_date'], name='corematoshr_last_da_204a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobnotification',
            index=models.Index(fields=['last_date'], name='corematoshr_last_da_9f3263_idx'),
        ),
        migrations.AddIndex(
            model_name='jobnotification',
            index=models.Index(fields=['organization'], name='corematoshr_organiz_a21a17_idx'),
        ),
        migrations.AddIndex(
            model_name='requireddocument',
            index=models.Index(fields=['service', 'document_name'], name='corematoshr_service_27dc8e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['approved', 'rating'], name='corematoshr_approve_05d7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='corematoshr_created_5ffd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['approved', '-created_at'], name='corematoshr_approve_d266fb_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['active', 'category'], name='corematoshr_active_d4e122_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='corematoshr_name_dc5bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecharge',
            index=models.Index(fields=['service'], name='corematoshr_service_6be089_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='corematoshr_role_8ca574_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='corematoshr_email_e1248f_idx'),
        ),
    ]
