# Generated by Django 6.0.2 on 2026-07-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0007_alter_user_options_alter_announcement_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_urgent',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Urgent'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_urgent'], name='corematoshr_is_urge_ef8e42_idx'),
        ),
    ]
