# Generated by Django 6.0.2 on 2026-07-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0008_announcement_is_urgent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Government Scheme', 'Government Scheme'), ('Recruitment', 'Recruitment'), ('Scholarship', 'Scholarship'), ('Holiday', 'Holiday'), ('Notice', 'Notice')], db_index=True, max_length=50, verbose_name='Category'),
        ),
    ]
