# Generated by Django 6.0.2 on 2026-07-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0009_alter_announcement_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('designation', models.CharField(max_length=200, verbose_name='Designation')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='corematoshr_is_acti_6a1716_idx')],
            },
        ),
    ]
