# Generated by Django 6.0.2 on 2026-07-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0010_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessinfo',
            name='logo',
        ),
    ]
