# Generated by Django 6.0.7 on 2026-07-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0011_remove_businessinfo_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(blank=True, help_text='e.g. example@upi', max_length=100, verbose_name='UPI ID')),
                ('upi_mobile', models.CharField(blank=True, max_length=15, verbose_name='UPI Mobile')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payments/', verbose_name='QR Code')),
                ('payment_instructions', models.TextField(blank=True, default='Scan QR code and pay using any UPI app.', verbose_name='Instructions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Payment Setting',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
