# Generated by Django 6.0.7 on 2026-07-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0012_paymentsettings_application_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('razorpay', 'Razorpay'), ('cash', 'Cash')], default='upi', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['payment_status'], name='corematoshr_payment_c09609_idx'),
        ),
    ]
