# Generated by Django 6.0.7 on 2026-07-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0013_application_payment_date_application_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_app',
            field=models.CharField(blank=True, choices=[('gpay', 'Google Pay'), ('phonepe', 'PhonePe'), ('paytm', 'Paytm'), ('bhim', 'BHIM'), ('upi', 'Other UPI App'), ('other', 'Other')], default='upi', max_length=20, verbose_name='Payment App'),
        ),
        migrations.AddField(
            model_name='application',
            name='utr_number',
            field=models.CharField(blank=True, help_text='Unique Transaction Reference (if available)', max_length=50, verbose_name='UTR Number'),
        ),
    ]
