# Generated by Django 6.0.7 on 2026-07-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0014_application_payment_app_application_utr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='payment_required',
            field=models.BooleanField(default=False, help_text='If enabled, users will be prompted to pay after application submission.', verbose_name='Payment Required'),
        ),
    ]
