# Generated by Django 6.0.7 on 2026-07-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0015_service_payment_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Approved'),
        ),
        migrations.AlterUniqueTogether(
            name='requireddocument',
            unique_together={('service', 'document_name')},
        ),
    ]
