# Generated by Django 6.0.7 on 2026-07-23 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0016_alter_review_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='cash_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable Cash Payment'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='razorpay_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable Razorpay'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='razorpay_key_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Razorpay Key ID'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, max_length=100, verbose_name='Razorpay Key Secret'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='razorpay_test_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='Razorpay Test Key'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='razorpay_test_secret',
            field=models.CharField(blank=True, max_length=100, verbose_name='Razorpay Test Secret'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='test_mode',
            field=models.BooleanField(default=False, verbose_name='Test Mode'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='upi_enabled',
            field=models.BooleanField(default=True, verbose_name='Enable UPI Payment'),
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Order Created'), ('captured', 'Payment Captured'), ('failed', 'Payment Failed'), ('refunded', 'Payment Refunded'), ('webhook_received', 'Webhook Received'), ('manual_confirmed', 'Manually Confirmed')], db_index=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('webhook_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='corematoshree.application')),
            ],
            options={
                'verbose_name': 'Payment Log',
                'verbose_name_plural': 'Payment Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'event_type'], name='corematoshr_applica_80b7ff_idx'), models.Index(fields=['razorpay_payment_id'], name='corematoshr_razorpa_fb94d2_idx')],
            },
        ),
    ]
