# Generated by Django 6.0.7 on 2026-07-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0017_paymentsettings_cash_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payment_app',
            field=models.CharField(blank=True, choices=[('gpay', 'Google Pay'), ('phonepe', 'PhonePe'), ('paytm', 'Paytm'), ('bhim', 'BHIM'), ('upi', 'Other UPI App'), ('other', 'Other')], max_length=20, null=True, verbose_name='Payment App'),
        ),
    ]
