# Generated by Django 6.0.7 on 2026-07-26 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0018_alter_application_payment_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requireddocument',
            options={'ordering': ['service__name', 'document_name'], 'verbose_name': 'Required Document', 'verbose_name_plural': 'Required Documents'},
        ),
        migrations.AlterModelOptions(
            name='servicecharge',
            options={'ordering': ['service__name'], 'verbose_name': 'Service Charge', 'verbose_name_plural': 'Service Charges'},
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='servicecharge',
            name='charge',
            field=models.DecimalField(decimal_places=2, help_text='Must be greater than or equal to 0.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Charge'),
        ),
    ]
