# Generated by Django 6.0.7 on 2026-07-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0019_alter_requireddocument_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentlog',
            name='corematoshr_razorpa_fb94d2_idx',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='razorpay_enabled',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='razorpay_key_id',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='razorpay_key_secret',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='razorpay_test_key',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='razorpay_test_secret',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='test_mode',
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('cash', 'Cash')], default='upi', max_length=20),
        ),
        migrations.RemoveField(
            model_name='paymentlog',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='paymentlog',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='paymentlog',
            name='webhook_data',
        ),
    ]
