# Generated by Django 6.0.7 on 2026-07-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0020_remove_paymentlog_corematoshr_razorpa_fb94d2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='gstin',
            field=models.CharField(blank=True, help_text='GST Identification Number (if applicable)', max_length=20, verbose_name='GSTIN'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Business logo for receipts and branding.', null=True, upload_to='business/', verbose_name='Logo'),
        ),
    ]
