# Generated by Django 6.0.7 on 2026-07-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0021_businessinfo_gstin_businessinfo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('cash', 'Cash'), ('manual', 'Manual')], default='upi', max_length=20),
        ),
    ]
