# Generated by Django 6.0.7 on 2026-07-29 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0022_alter_application_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='utr_number',
            field=models.CharField(blank=True, help_text='Unique Transaction Reference (if available)', max_length=50, validators=[django.core.validators.RegexValidator(message='UTR number must be 12–16 alphanumeric characters.', regex='^[A-Za-z0-9]{12,16}$')], verbose_name='UTR Number'),
        ),
    ]
