# Generated by Django 6.0.7 on 2026-08-03 13:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0024_announcement_updated_at_service_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Razorpay Order ID'),
        ),
        migrations.AddField(
            model_name='application',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Razorpay Payment ID'),
        ),
        migrations.AddField(
            model_name='application',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razorpay Signature'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('cash', 'Cash'), ('manual', 'Manual'), ('razorpay', 'Razorpay')], default='upi', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Payment Transaction ID'),
        ),
        migrations.AlterField(
            model_name='application',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Receipt Number'),
        ),
        migrations.AlterField(
            model_name='application',
            name='utr_number',
            field=models.CharField(blank=True, help_text='Unique Transaction Reference (if available)', max_length=50, validators=[django.core.validators.RegexValidator(message='UTR number must be 12-16 alphanumeric characters.', regex='^[A-Za-z0-9]{12,16}$')], verbose_name='UTR Number'),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='corematoshree.application', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='corematoshree.application', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='event_type',
            field=models.CharField(choices=[('created', 'Order Created'), ('captured', 'Payment Captured'), ('failed', 'Payment Failed'), ('refunded', 'Payment Refunded'), ('webhook_received', 'Webhook Received'), ('manual_confirmed', 'Manually Confirmed')], db_index=True, max_length=50, verbose_name='Event Type'),
        ),
    ]
