# Generated by Django 6.0.7 on 2026-08-04 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0026_application_gst_on_fee_application_razorpay_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governmentscheme',
            options={'ordering': ['-created_at'], 'verbose_name': 'Government Scheme', 'verbose_name_plural': 'Government Schemes'},
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='apply_link',
            field=models.URLField(blank=True, verbose_name='Apply Link'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='benefits',
            field=models.TextField(blank=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='District (if applicable)'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='official_link',
            field=models.URLField(blank=True, verbose_name='Official Link'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='provider',
            field=models.CharField(choices=[('central', 'Central Government'), ('state', 'State Government'), ('joint', 'Joint Venture (Central & State)'), ('district', 'District Level')], default='state', max_length=20, verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='source',
            field=models.CharField(default='manual', max_length=100, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ongoing', 'Ongoing'), ('upcoming', 'Upcoming'), ('closed', 'Closed'), ('expired', 'Expired')], db_index=True, default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='eligibility',
            field=models.TextField(blank=True, verbose_name='Eligibility Criteria'),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='schemes/', verbose_name='Banner/Image'),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Scheme Title'),
        ),
        migrations.AddIndex(
            model_name='governmentscheme',
            index=models.Index(fields=['status', 'provider'], name='corematoshr_status_3735f9_idx'),
        ),
        migrations.AddIndex(
            model_name='governmentscheme',
            index=models.Index(fields=['district'], name='corematoshr_distric_795e21_idx'),
        ),
        migrations.AddIndex(
            model_name='governmentscheme',
            index=models.Index(fields=['category'], name='corematoshr_categor_8e6126_idx'),
        ),
    ]
