# Generated by Django 5.2.17 on 2026-10-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corematoshree', '0029_verification_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='admin_note',
        ),
        migrations.RemoveField(
            model_name='application',
            name='rejection_reason',
        ),
        migrations.AlterField(
            model_name='application',
            name='application_number',
            field=models.CharField(blank=True, db_index=True, help_text='Public tracking number shown to the customer.', max_length=40, null=True, unique=True, verbose_name='Application Number'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_number'], name='corematoshr_applica_8be933_idx'),
        ),
    ]
